#!/usr/bin/env bash

cd "$FORNIX_FOLDER"
# make sure tauri is installed (pinned to tauri next-branch ~v1.0.0-beta.7 2021-1-28)
cargo install --git https://github.com/tauri-apps/tauri/ --rev efbf236f35a1dd4064c0615b56881e4132a249f4 tauri-cli

cd "$FORNIX_FOLDER/packages/src-tauri"
cargo install --path .

# backend
cd "$FORNIX_FOLDER/packages"
# cargo tauri icon src-tauri/app-icon.png
cargo tauri build --verbose "$@"