#!/usr/bin/env bash


# make sure tauri is installed (pinned to tauri next-branch ~v1.0.0-beta.7 2021-1-28)
cargo install --git https://github.com/tauri-apps/tauri/ --rev efbf236f35a1dd4064c0615b56881e4132a249f4 tauri-cli
# FIXME: add this^ to startup instead of here

cd "$FORNIX_FOLDER/packages/src-tauri"
cargo install --path .

# backend
cd "$FORNIX_FOLDER/packages"
cargo tauri dev --verbose "$@"